### ISSUE TITLE
Cannot navigate back/forward from image/binary files

### ISSUE THREAD

**Issue by abose** [phcode-dev/phoenix#847]
### Describe the bug

Cannot navigate back/forward from image/binary files.

### Reproduction

1. Open default project. Select index.html
2. Open png file in images folder.
3. Click on back button
4. observe that nothing happens and error message in console.

### Expected behavior

nav back and forward should work

### OS, Browser and Phoenix versions

all

### logs or debug stack trace if any

```shell
NavigationProvider.js:411 Uncaught TypeError: Cannot read properties of null (reading '_codeMirror')
    at _navigateBack (NavigationProvider.js:411:58)
    at HTMLDivElement._navigateBackClicked (NavigationProvider.js:625:13)
    at HTMLDivElement.dispatch (jquery-2.1.3.min.js:3:6444)
    at r.handle (jquery-2.1.3.min.js:3:3219)
```

**Comment by abose** [comment]
This is fixed.
Closing.
